version: "3"

services:
  apache:
    build: apache
    env_file: .env
    depends_on:
      - php
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ${PROJECT_ROOT}:/var/www/html:rw,delegated
    tty: true

  maildev:
    image: djfarrelly/maildev:latest
    env_file: .env
    depends_on:
      - apache
    ports:
      - ${MAILDEV_PORT}:80

  mysql:
    image: mysql:5
    env_file: .env
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./database:/var/lib/mysql
    tty: true

  php:
    build: php
    env_file: .env
    volumes:
      - ${PROJECT_ROOT}:/var/www/html:rw,delegated
    tty: true
